version: "3.8"

services:
  django:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    command: gunicorn skule_vote.wsgi:application --bind 0.0.0.0:8001 --workers 5 --capture-output --access-logfile - --error-logfile -
    ports:
      - 8002:8002
    env_file: .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
